//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELTEM_Kütüphane_Otomasyonu_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.genel_kayitlar_1 = new HashSet<genel_kayitlar_1>();
        }
    
        public int kitap_barkod { get; set; }
        public string kitap_ad { get; set; }
        public string kitap_yazar { get; set; }
        public string kitap_yayınevi { get; set; }
        public Nullable<int> kitap_sayfasayısı { get; set; }
        public Nullable<System.DateTime> kitap_basımtarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genel_kayitlar_1> genel_kayitlar_1 { get; set; }
    }
}
