//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELTEM_Kütüphane_Otomasyonu_
{
    using System;
    using System.Collections.Generic;
    
    public partial class üyeler_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public üyeler_1()
        {
            this.genel_kayitlar_1 = new HashSet<genel_kayitlar_1>();
        }
    
        public int üye_no { get; set; }
        public string üye_adsoyad { get; set; }
        public Nullable<int> üye_sınıf { get; set; }
        public string üye_cinsiyet { get; set; }
        public string üye_gsm { get; set; }
        public string üye_eposta { get; set; }
        public string üye_eposta_türü { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genel_kayitlar_1> genel_kayitlar_1 { get; set; }
    }
}
